name: Refresh Data

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 2,14 * * *'

jobs:
  refreshData:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out tool

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore src/CovidAus/CovidAus.csproj

    - name: Build
      run: dotnet build src/CovidAus/CovidAus.csproj --configuration Release --no-restore 
    
    - name: Run
      run: dotnet run --project src/CovidAus/CovidAus.csproj

    - name: Upload data to data repo
      run: |
        mkdir temp
        
        git config --global user.email "actions"
        git config --global user.name "actions"
        git clone "https://${{ secrets.REPO_TOKEN }}@github.com/dylanlerch/covid-aus-data.git" temp

        cp covid-temp/data.json temp
        cd temp

        {
          git add .
        } && {
          git commit -m "Update data at $(date +'%Y-%m-%dT%H:%M:%S')UTC"
        } && {
          git push origin master
        } || true
